[package]
name = "image_extender"
version = "0.1.0"
edition = "2021"

[dependencies]
image = { version = "0.25", features = ["png"] }
clap = { version = "4.4", features = ["derive"] }
walkdir = "2.4"
